/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package hm19071;

import javax.swing.JOptionPane;

/**
 *
 * @author academica
 */
public class TicTacToe extends javax.swing.JFrame {
    String jugador;
    Boolean boton1 = true,boton2 = true, boton3 = true, boton4 = true, boton5 = true, boton6 = true, boton7 = true, boton8 = true, boton9 = true, accionJugador;
    public TicTacToe() {
        
        initComponents();
        if(rbtnEquis.isSelected()){
           jugador = "X";
           accionJugador = true;
        }
        if(rbtnCero.isSelected()){
           jugador = "O";
           accionJugador = false;
        }
        btn01.setEnabled(false);
        btn02.setEnabled(false);
        btn03.setEnabled(false);
        btn04.setEnabled(false);
        btn05.setEnabled(false);
        btn06.setEnabled(false);
        btn07.setEnabled(false);
        btn08.setEnabled(false);
        btn09.setEnabled(false);
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        agrupacion = new javax.swing.ButtonGroup();
        agrupacionBotones = new javax.swing.ButtonGroup();
        rbtnEquis = new javax.swing.JRadioButton();
        rbtnCero = new javax.swing.JRadioButton();
        btnReiniciar = new javax.swing.JButton();
        lblPreguntaInicioJuego = new javax.swing.JLabel();
        btn07 = new javax.swing.JButton();
        btn05 = new javax.swing.JButton();
        btn02 = new javax.swing.JButton();
        btn03 = new javax.swing.JButton();
        btn01 = new javax.swing.JButton();
        btn06 = new javax.swing.JButton();
        btn04 = new javax.swing.JButton();
        btn08 = new javax.swing.JButton();
        btn09 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        agrupacion.add(rbtnEquis);
        rbtnEquis.setText("Equis");
        rbtnEquis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnEquisActionPerformed(evt);
            }
        });

        agrupacion.add(rbtnCero);
        rbtnCero.setText("Cero");
        rbtnCero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnCeroActionPerformed(evt);
            }
        });

        btnReiniciar.setText("REINICIAR EL JUEGO");
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        lblPreguntaInicioJuego.setText("QUIEN INICIA EL JUEGO?");

        btn07.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btn07.setToolTipText("");
        agrupacionBotones.add(btn07);
        btn07.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn07ActionPerformed(evt);
            }
        });

        btn05.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btn05.setToolTipText("");
        agrupacionBotones.add(btn05);
        btn05.setMaximumSize(new java.awt.Dimension(2, 6));
        btn05.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn05ActionPerformed(evt);
            }
        });

        btn02.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btn02.setToolTipText("");
        agrupacionBotones.add(btn02);
        btn02.setMaximumSize(new java.awt.Dimension(2, 6));
        btn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn02ActionPerformed(evt);
            }
        });

        btn03.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btn03.setToolTipText("");
        agrupacionBotones.add(btn03);
        btn03.setMaximumSize(new java.awt.Dimension(2, 6));
        btn03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn03ActionPerformed(evt);
            }
        });

        btn01.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btn01.setToolTipText("");
        agrupacionBotones.add(btn01);
        btn01.setMaximumSize(new java.awt.Dimension(2, 6));
        btn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn01ActionPerformed(evt);
            }
        });

        btn06.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btn06.setToolTipText("");
        agrupacionBotones.add(btn06);
        btn06.setMaximumSize(new java.awt.Dimension(2, 6));
        btn06.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn06ActionPerformed(evt);
            }
        });

        btn04.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btn04.setToolTipText("");
        agrupacionBotones.add(btn04);
        btn04.setMaximumSize(new java.awt.Dimension(2, 6));
        btn04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn04ActionPerformed(evt);
            }
        });

        btn08.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btn08.setToolTipText("");
        agrupacionBotones.add(btn08);
        btn08.setMaximumSize(new java.awt.Dimension(2, 6));
        btn08.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn08ActionPerformed(evt);
            }
        });

        btn09.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        btn09.setToolTipText("");
        agrupacionBotones.add(btn09);
        btn09.setMaximumSize(new java.awt.Dimension(2, 6));
        btn09.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn09ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblPreguntaInicioJuego)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnReiniciar)
                        .addGap(28, 28, 28))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(rbtnEquis)
                        .addGap(27, 27, 27)
                        .addComponent(rbtnCero)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(btn01, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(btn04, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn05, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btn07, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn08, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn03, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReiniciar)
                    .addComponent(lblPreguntaInicioJuego))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnEquis)
                    .addComponent(rbtnCero))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn02, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn06, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn04, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn05, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn08, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn07, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btn09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(34, 34, 34))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn05ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn05ActionPerformed
        if (boton5 == true) {
           if(accionJugador == true){
                 btn05.setText(String.valueOf("X"));
                 accionJugador = false;
            }else{
                 btn05.setText(String.valueOf("O"));
                 accionJugador = true;
            } 
            boton5 = false;
           btn05.setEnabled(false);
           ganador();
        } else {
            
        }
            
    }//GEN-LAST:event_btn05ActionPerformed

    private void btn09ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn09ActionPerformed
        if (boton9 == true) {
             if(accionJugador == true){
                 btn09.setText(String.valueOf("X"));
                 accionJugador = false;
            }else{
                 btn09.setText(String.valueOf("O"));
                 accionJugador = true;
            }
              boton9 = false;
              btn09.setEnabled(false);
              ganador();
              
        } else {
        }
    }//GEN-LAST:event_btn09ActionPerformed

    private void btn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn01ActionPerformed

        if (boton1 == true) {
           
            if(accionJugador == true){
                 btn01.setText(String.valueOf("X"));
                 accionJugador = false;
            }else{
                 btn01.setText(String.valueOf("O"));
                 accionJugador = true;
            }
             boton1 = false;
             btn01.setEnabled(false);
             ganador();
        } else {
        }
    }//GEN-LAST:event_btn01ActionPerformed

    private void rbtnEquisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnEquisActionPerformed
        if(rbtnEquis.isSelected()){
        jugador = "X";
        accionJugador = true;
        btn01.setEnabled(true);
        btn02.setEnabled(true);
        btn03.setEnabled(true);
        btn04.setEnabled(true);
        btn05.setEnabled(true);
        btn06.setEnabled(true);
        btn07.setEnabled(true);
        btn08.setEnabled(true);
        btn09.setEnabled(true);
        rbtnCero.setEnabled(false);
        rbtnEquis.setEnabled(false);
        }
    }//GEN-LAST:event_rbtnEquisActionPerformed

    private void rbtnCeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnCeroActionPerformed
        if(rbtnCero.isSelected()){
           jugador = "O";
           accionJugador = false;
           btn01.setEnabled(true);
        btn02.setEnabled(true);
        btn03.setEnabled(true);
        btn04.setEnabled(true);
        btn05.setEnabled(true);
        btn06.setEnabled(true);
        btn07.setEnabled(true);
        btn08.setEnabled(true);
        btn09.setEnabled(true);
        }
    }//GEN-LAST:event_rbtnCeroActionPerformed

    private void btn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn02ActionPerformed
       if(boton2 == true){
            if(accionJugador == true){
                 btn02.setText(String.valueOf("X"));
                 accionJugador = false;
            }else{
                 btn02.setText(String.valueOf("O"));
                 accionJugador = true;
            }
             boton2 = false;
             btn02.setEnabled(false);
             ganador();
       }else{
       
       }
    }//GEN-LAST:event_btn02ActionPerformed

    private void btn03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn03ActionPerformed
        if (boton3 == true) {
            if(accionJugador == true){
                 btn03.setText(String.valueOf("X"));
                 accionJugador = false;
            }else{
                 btn03.setText(String.valueOf("O"));
                 accionJugador = true;
            }
             boton3 = false;
             btn03.setEnabled(false);
             ganador();
        } else {
        }
            
    }//GEN-LAST:event_btn03ActionPerformed

    private void btn04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn04ActionPerformed
        if (boton4 == true) {
            if(accionJugador == true){
                 btn04.setText(String.valueOf("X"));
                 accionJugador = false;
            }else{
                 btn04.setText(String.valueOf("O"));
                 accionJugador = true;
            } 
             boton4 = false;
             btn04.setEnabled(false);
             ganador();
        } else {
        }
           
    }//GEN-LAST:event_btn04ActionPerformed

    private void btn06ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn06ActionPerformed
        if (boton6 == true) {
             if(accionJugador == true){
                 btn06.setText(String.valueOf("X"));
                 accionJugador = false;
            }else{
                 btn06.setText(String.valueOf("O"));
                 accionJugador = true;
            }
              boton6 = false;
             btn06.setEnabled(false);
             ganador();
        } else {
        }
           
    }//GEN-LAST:event_btn06ActionPerformed

    private void btn07ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn07ActionPerformed
        if (boton7 == true) {
             if(accionJugador == true){
                 btn07.setText(String.valueOf("X"));
                 accionJugador = false;
            }else{
                 btn07.setText(String.valueOf("O"));
                 accionJugador = true;
            }
              boton7 = false;
              btn07.setEnabled(false);
              ganador();
        } else {
        }
    }//GEN-LAST:event_btn07ActionPerformed

    private void btn08ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn08ActionPerformed
        if (boton8 == true) {
             if(accionJugador == true){
                 btn08.setText(String.valueOf("X"));
                 accionJugador = false;
            }else{
                 btn08.setText(String.valueOf("O"));
                 accionJugador = true;
            }
              boton8 = false;
              btn08.setEnabled(false);
              ganador();
        } else {
        }
    }//GEN-LAST:event_btn08ActionPerformed
    private void reiniciar(){
    btn01.setEnabled(false);
        btn02.setEnabled(false);
        btn03.setEnabled(false);
        btn04.setEnabled(false);
        btn05.setEnabled(false);
        btn06.setEnabled(false);
        btn07.setEnabled(false);
        btn08.setEnabled(false);
        btn09.setEnabled(false);
        
        btn01.setText("");
        btn02.setText("");
        btn03.setText("");
        btn04.setText("");
        btn05.setText("");
        btn06.setText("");
        btn07.setText("");
        btn08.setText("");
        btn09.setText("");
        agrupacion.clearSelection();
        
        boton1 = true;
        boton2 = true;
        boton3 = true;
        boton4 = true;
        boton5 = true;
        boton6 = true;
        boton7 = true;
        boton8 = true;
        boton9 = true;
        jugador = "";
        rbtnCero.setEnabled(true);
        rbtnEquis.setEnabled(true);
        
    }
    private void bloqueo(){
    btn01.setEnabled(false);
        btn02.setEnabled(false);
        btn03.setEnabled(false);
        btn04.setEnabled(false);
        btn05.setEnabled(false);
        btn06.setEnabled(false);
        btn07.setEnabled(false);
        btn08.setEnabled(false);
        btn09.setEnabled(false);
    }
    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        reiniciar();
    }//GEN-LAST:event_btnReiniciarActionPerformed
    public void ganador(){
        //FILAS X
        if(btn01.getText()== "X" && btn02.getText()== "X" && btn03.getText()== "X"){
          JOptionPane.showMessageDialog(null, "GANADOR X");
        bloqueo();
        }else
        if(btn04.getText()== "X" && btn05.getText()== "X" && btn06.getText()== "X"){
          JOptionPane.showMessageDialog(null, "GANADOR X");
       bloqueo();
        }else
        if(btn07.getText()== "X" && btn08.getText()== "X" && btn09.getText()== "X"){
          JOptionPane.showMessageDialog(null, "GANADOR X");
   bloqueo();
        }else
        //FILAS O
        if(btn01.getText()== "O" && btn02.getText()== "O" && btn03.getText()== "O"){
          JOptionPane.showMessageDialog(null, "GANADOR O");
        bloqueo();
        }else
        if(btn04.getText()== "O" && btn05.getText()== "O" && btn06.getText()== "O"){
          JOptionPane.showMessageDialog(null, "GANADOR O");
          bloqueo();
        }else
        if(btn07.getText()== "O" && btn08.getText()== "O" && btn09.getText()== "O"){
          JOptionPane.showMessageDialog(null, "GANADOR O");
          bloqueo();
        }else
        //COLUMNAS X
        if(btn01.getText()== "X" && btn04.getText()== "X" && btn07.getText()== "X"){
          JOptionPane.showMessageDialog(null, "GANADOR X");
           bloqueo();
        }else
        if(btn02.getText()== "X" && btn05.getText()== "X" && btn08.getText()== "X"){
          JOptionPane.showMessageDialog(null, "GANADOR X");
             bloqueo();
        }else
        if(btn03.getText()== "X" && btn06.getText()== "X" && btn09.getText()== "X"){
          JOptionPane.showMessageDialog(null, "GANADOR X");
       bloqueo();
        }else
        //COLUMNAS O
        if(btn01.getText()== "O" && btn04.getText()== "O" && btn07.getText()== "O"){
          JOptionPane.showMessageDialog(null, "GANADOR O");
          bloqueo();
        }else
        if(btn02.getText()== "O" && btn05.getText()== "O" && btn08.getText()== "O"){
          JOptionPane.showMessageDialog(null, "GANADOR O");
           bloqueo();
        }else
        if(btn03.getText()== "O" && btn06.getText()== "O" && btn09.getText()== "O"){
          JOptionPane.showMessageDialog(null, "GANADOR O");
           bloqueo();
        }else
        //DIAGONALES X
        if(btn01.getText()== "X" && btn05.getText()== "X" && btn09.getText()== "X"){
          JOptionPane.showMessageDialog(null, "GANADOR X");
           bloqueo();
        }else
        if(btn03.getText()== "X" && btn05.getText()== "X" && btn07.getText()== "X"){
          JOptionPane.showMessageDialog(null, "GANADOR X");
           bloqueo();
        }else
        //DIAGONALES 0
        if(btn01.getText()== "O" && btn05.getText()== "O" && btn09.getText()== "O"){
          JOptionPane.showMessageDialog(null, "GANADOR O");
           bloqueo();
        }else
        if(btn03.getText()== "O" && btn05.getText()== "O" && btn07.getText()== "O"){
          JOptionPane.showMessageDialog(null, "GANADOR O");
           bloqueo();
        }else
        if (boton1 == false && boton2 == false && boton3 == false && boton4 == false && boton5 == false && boton6 == false && boton7 == false && boton8 == false && boton9 == false) {
            JOptionPane.showMessageDialog(null, "EMPATE");
           bloqueo();
        }
        
        
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTacToe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTacToe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup agrupacion;
    private javax.swing.ButtonGroup agrupacionBotones;
    private javax.swing.JButton btn01;
    private javax.swing.JButton btn02;
    private javax.swing.JButton btn03;
    private javax.swing.JButton btn04;
    private javax.swing.JButton btn05;
    private javax.swing.JButton btn06;
    private javax.swing.JButton btn07;
    private javax.swing.JButton btn08;
    private javax.swing.JButton btn09;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JLabel lblPreguntaInicioJuego;
    private javax.swing.JRadioButton rbtnCero;
    private javax.swing.JRadioButton rbtnEquis;
    // End of variables declaration//GEN-END:variables
}
