/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package maquina.expendedora;

import javax.swing.DefaultListModel;

/**
 *
 * @author pc
 */
public class maquina extends javax.swing.JFrame {

    DefaultListModel modeloProductos = new DefaultListModel();
    DefaultListModel modeloPrecios = new DefaultListModel();   
    DefaultListModel modeloExistencias = new DefaultListModel();
    DefaultListModel modeloCantidad = new DefaultListModel();
    double total;
    int totalExistencias;
    
    public maquina() {
        initComponents();
        lblTotal.setText(String.valueOf("$ " + 0.0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstProductos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstPrecios = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstExistencias = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstProductosSeleccionados = new javax.swing.JList<>();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstPrecioProductoSeleccionado = new javax.swing.JList<>();
        btnAgregar = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        btnComprar = new javax.swing.JButton();
        lblNombreTotal = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblMaquinaExpendedora = new javax.swing.JLabel();
        lblNombreCaja = new javax.swing.JLabel();
        lblCaja = new javax.swing.JLabel();
        lblProductos = new javax.swing.JLabel();
        lblPrecio = new javax.swing.JLabel();
        lblExistencias = new javax.swing.JLabel();
        lblProductosSeleccionados = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lstProductos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "soda   1", "soda   2", "combo 1", "combo 2" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstProductos.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstProductosValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstProductos);

        lstPrecios.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "1.0", "1.0", "5.0", "4.0" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstPrecios.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPreciosValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstPrecios);

        lstExistencias.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "20", "20", "20", "20" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstExistencias.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstExistenciasValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstExistencias);

        lstProductosSeleccionados.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstProductosSeleccionadosValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstProductosSeleccionados);

        lstPrecioProductoSeleccionado.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPrecioProductoSeleccionadoValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(lstPrecioProductoSeleccionado);

        btnAgregar.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnQuitar.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnQuitar.setText("QUITAR");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        btnComprar.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        btnComprar.setText("COMPRAR");

        lblNombreTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombreTotal.setText("Total: ");

        lblTotal.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTotal.setText("$");

        lblMaquinaExpendedora.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblMaquinaExpendedora.setText("MAQUINA EXPENDEDORA");

        lblNombreCaja.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombreCaja.setText("Caja:");

        lblCaja.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCaja.setText("$");

        lblProductos.setText("Productos");

        lblPrecio.setText("Precio");

        lblExistencias.setText("Existencias");

        lblProductosSeleccionados.setText("Productos Seleccionados");

        jLabel10.setText("Precio");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblProductos)
                                .addGap(108, 108, 108)
                                .addComponent(lblPrecio)
                                .addGap(18, 18, 18)
                                .addComponent(lblExistencias))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnQuitar, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProductosSeleccionados))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombreCaja)
                                .addGap(18, 18, 18)
                                .addComponent(lblCaja)
                                .addGap(394, 394, 394)
                                .addComponent(lblNombreTotal)
                                .addGap(18, 18, 18)
                                .addComponent(lblTotal))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(205, 205, 205)
                                .addComponent(lblMaquinaExpendedora)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblMaquinaExpendedora)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblProductos)
                            .addComponent(lblPrecio)
                            .addComponent(lblExistencias)
                            .addComponent(lblProductosSeleccionados)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane4)
                            .addComponent(jScrollPane5)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnAgregar)
                        .addGap(18, 18, 18)
                        .addComponent(btnQuitar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnComprar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNombreCaja)
                        .addComponent(lblCaja))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNombreTotal)
                        .addComponent(lblTotal)))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        int posicion;
        posicion = lstExistencias.getSelectedIndex();
        totalExistencias = 0;
        modeloProductos.addElement(lstProductos.getSelectedValue());
        modeloPrecios.addElement(lstPrecios.getSelectedValue());
        modeloExistencias.addElement(lstExistencias.getSelectedValue());
        total=total+Double.parseDouble(lstPrecios.getSelectedValue());
        lstProductosSeleccionados.setModel(modeloProductos);
        lstPrecioProductoSeleccionado.setModel(modeloPrecios);
        lblTotal.setText(String.valueOf(total));
        modeloExistencias.set(posicion, posicion);
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
      int posicion;
      posicion=lstProductosSeleccionados.getSelectedIndex();
      total=total-Double.parseDouble(lstPrecioProductoSeleccionado.getSelectedValue());
      modeloProductos.remove(posicion);
      modeloPrecios.remove(posicion);
      lstProductosSeleccionados.setModel(modeloProductos);
      lstPrecioProductoSeleccionado.setModel(modeloPrecios);
      lblTotal.setText(String.valueOf(total));
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void lstProductosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstProductosValueChanged
        int posicion;
        posicion=lstProductos.getSelectedIndex();
        lstPrecios.setSelectedIndex(posicion);
        lstExistencias.setSelectedIndex(posicion);
    }//GEN-LAST:event_lstProductosValueChanged

    private void lstPreciosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPreciosValueChanged
        int posicion;
        posicion=lstPrecios.getSelectedIndex();
        lstProductos.setSelectedIndex(posicion);
        lstExistencias.setSelectedIndex(posicion);
    }//GEN-LAST:event_lstPreciosValueChanged

    private void lstExistenciasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstExistenciasValueChanged
        int posicion;
        posicion = lstExistencias.getSelectedIndex();
        lstPrecios.setSelectedIndex(posicion);
        lstProductos.setSelectedIndex(posicion);
    }//GEN-LAST:event_lstExistenciasValueChanged

    private void lstProductosSeleccionadosValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstProductosSeleccionadosValueChanged
       int posicion;
       posicion=lstProductosSeleccionados.getSelectedIndex();
       lstPrecioProductoSeleccionado.setSelectedIndex(posicion);
    }//GEN-LAST:event_lstProductosSeleccionadosValueChanged

    private void lstPrecioProductoSeleccionadoValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPrecioProductoSeleccionadoValueChanged
        int posicion;
        posicion=lstPrecioProductoSeleccionado.getSelectedIndex();
        lstProductosSeleccionados.setSelectedIndex(posicion);
    }//GEN-LAST:event_lstPrecioProductoSeleccionadoValueChanged
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(maquina.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new maquina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblCaja;
    private javax.swing.JLabel lblExistencias;
    private javax.swing.JLabel lblMaquinaExpendedora;
    private javax.swing.JLabel lblNombreCaja;
    private javax.swing.JLabel lblNombreTotal;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblProductos;
    private javax.swing.JLabel lblProductosSeleccionados;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JList<String> lstExistencias;
    private javax.swing.JList<String> lstPrecioProductoSeleccionado;
    private javax.swing.JList<String> lstPrecios;
    private javax.swing.JList<String> lstProductos;
    private javax.swing.JList<String> lstProductosSeleccionados;
    // End of variables declaration//GEN-END:variables
}
